### PR TITLE
Return Account for successful sign-in

### PR DESCRIPTION
**Pull request by chanseokoh**
I realized that `logIn()` should return `Account` instead of `boolean` so that a caller knows which `Account` a user signed in with.

### CODE REVIEW

**Comment by elharo** [comment]
What if instead of returning null on a failed login we threw an exception? Does that make sense? I.e. is a failed login an exceptional condition a client should check for? If we don't do that, they may get an unhandled NullPointerException instead.

**Comment by chanseokoh** [comment]
It's not always an exceptional case. For example, we allow users to simply log in with the G icon, not doing anything with after login. So I think returning an exception is an overkill.

**Comment by chanseokoh** [comment]
Forgot to say that users can cancel login in that case.

**Comment by elharo** [comment]
LGTM assuming tests pass

**Pull request merged**
