### PR TITLE
Add eclipse file to .gitignore

### LINKED ISSUE #5: Add eclipse file to .gitignore
.classpath
	.project
	.settings/

### PR DESCRIPTION
**Pull request by elharo**
@akerekes close #5

### CODE REVIEW

**Comment by akerekes** [comment]
@elharo 
All of these are going to be generated via m2e and thus redundant to store them, right?

**Comment by elharo** [comment]
Eclipse is not assumed in this project.

**Comment by elharo** [comment]
But yhes, m2e will generate them on import.

**Comment by akerekes** [comment]
LGTM

**Pull request merged**
