### PR TITLE
Add OSGi metadata for use within Eclipse/OSGi

### PR DESCRIPTION
**Pull request by briandealwis**
Use the Felix `maven-bundle-plugin` to generate OSGi metadata to allow the jar to be treated as a bundle.

PTAL @elharo

### CODE REVIEW

**Comment by briandealwis** [comment]
I signed it!

**Comment by briandealwis** [comment]
Generated `META-INF/MANIFEST.MF` (sorted for clarity):
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Login Support for Google Cloud Tools
Bundle-SymbolicName: com.google.cloud.tools.ide.login
Bundle-Version: 0.0.0.SNAPSHOT
Export-Package: com.google.cloud.tools.ide.login;uses:="com.google.api.client.auth.oauth2,com.google.api.client.googleapis.auth.oauth2,com.google.api.client.http,javax.annotation";version="0.0.0"
Import-Package: com.google.api.client.auth.oauth2,
  com.google.api.client.googleapis.auth.oauth2,
  com.google.api.client.http,
  com.google.api.client.http.javanet,
  com.google.api.client.json,
  com.google.api.client.json.jackson,
  com.google.common.collect;version="[19.0,20)",
  javax.annotation
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
Tool: Bnd-3.0.0.201509101326
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_74
Archiver-Version: Plexus Archiver
Built-By: bsd
Bnd-LastModified: 1458678086990
```
Hmm, now that I think about it, I think it would be better to explicitly generate a `Bundle-RequireExecutionEnvironment` header too.

**Comment by briandealwis** [comment]
`MANIFEST.MF` now looks like:
```
Manifest-Version: 1.0
Bundle-Name: Login Support for Google Cloud Tools
Bundle-SymbolicName: com.google.cloud.tools.ide.login
Bundle-Version: 0.0.0.SNAPSHOT
Bundle-ManifestVersion: 2
Export-Package: com.google.cloud.tools.ide.login;version="0.0.0";uses:="com.google.api.client.auth.oauth2,com.google.api.client.googleapis.auth.oauth2,com.google.api.client.http,javax.annotation"
Import-Package: com.google.api.client.auth.oauth2,
  com.google.api.client.googleapis.auth.oauth2,
  com.google.api.client.http,
  com.google.api.client.http.javanet,
  com.google.api.client.json,
  com.google.api.client.json.jackson,
  com.google.common.collect;version="[19.0,20)",
  javax.annotation
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_74
Archiver-Version: Plexus Archiver
Built-By: bsd
Originally-Created-By: Apache Maven Bundle Plugin
Tool: Bnd-3.0.0.201509101326
Bnd-LastModified: 1458679108447
```

**Comment by elharo** [comment]
LGTM

**Comment by briandealwis** [comment]
Are we squashing commits on die-login?

**Comment by elharo** [comment]
Yes, we squash commits everywhere.

On Tue, Mar 22, 2016 at 7:13 PM, Brian de Alwis <notifications@github.com>
wrote:

> Are we squashing commits on die-login?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/ide-login/pull/12#issuecomment-200073804>
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Pull request merged**
